[logging]
level = "info"
target = "stdout"
color = "auto"
file_name = "./netscanner.log"
file_size_limit = 0
syslog_network = "tcp"
syslog_address = "localhost:601"
syslog_encoding = "rfc5424"
syslog_facility = 4

[server]
address = "localhost:0"
protocol = "http"
cert_file = ""
key_file = ""
public_url = ""
trusted_proxies = [ ]
trusted_headers = [ ]
allowed_origins = [ ]
access_log = ""
access_log_size_limit = 0

[datastore]
type = "memory"

[datastore.memory]

[datastore.sqlite]
file = "./netscanner.db"

[datastore.postgres]
address = "localhost:5432"
db = "netscanner"
user = "netscanner"
password = ""

[metrics]
enabled = false
path = "/metrics"
process = false
sensors = true

[sync]
mode = "disable"
address = ":50051"
crt_file = "./node.crt"
key_file = "./node.key"
ca_file = "./ca.crt"

[sensors]
include = "./sensors.d"
default_host = ""

[arp_cache]
ttl = "1h"

[dns]
provider = "system"
domains = []

[dns.system]

[dns.custom]
network = "udp"
address = "localhost:53"

[geoip]
provider = "none"
address_url_template = "https://whois.domaintools.com/{{.Address}}"
location_url_template = "https://maps.google.com/?q={{.Lat}},{{.Lng}}"

[geoip.none]

[geoip.maxminddb]
file = "./GeoLite2-City.mmdb"