[logging]
level = "info"
target = "stdout"
color = "auto"
file_name = "./netscanner.log"
file_size_limit = 0
syslog_network = "tcp"
syslog_address = "localhost:601"
syslog_encoding = "rfc5424"
syslog_facility = 4

[server]
address = "localhost:9123"
protocol = "http"
cert_file = ""
key_file = ""
public_url = ""
trusted_proxies = [ ]
trusted_headers = [ ]
allowed_origins = []
access_log = ""
access_log_size_limit = 0

[metrics]
enabled = false
path = "/metrics"
process = false
sensors = true