// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: sensor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventStreamer_SendEvent_FullMethodName = "/sensor.EventStreamer/SendEvent"
)

// EventStreamerClient is the client API for EventStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventStreamerClient interface {
	SendEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type eventStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStreamerClient(cc grpc.ClientConnInterface) EventStreamerClient {
	return &eventStreamerClient{cc}
}

func (c *eventStreamerClient) SendEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, EventStreamer_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStreamerServer is the server API for EventStreamer service.
// All implementations must embed UnimplementedEventStreamerServer
// for forward compatibility.
type EventStreamerServer interface {
	SendEvent(context.Context, *Event) (*EmptyResponse, error)
	mustEmbedUnimplementedEventStreamerServer()
}

// UnimplementedEventStreamerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStreamerServer struct{}

func (UnimplementedEventStreamerServer) SendEvent(context.Context, *Event) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedEventStreamerServer) mustEmbedUnimplementedEventStreamerServer() {}
func (UnimplementedEventStreamerServer) testEmbeddedByValue()                       {}

// UnsafeEventStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStreamerServer will
// result in compilation errors.
type UnsafeEventStreamerServer interface {
	mustEmbedUnimplementedEventStreamerServer()
}

func RegisterEventStreamerServer(s grpc.ServiceRegistrar, srv EventStreamerServer) {
	// If the following call panics, it indicates UnimplementedEventStreamerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStreamer_ServiceDesc, srv)
}

func _EventStreamer_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStreamerServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStreamer_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStreamerServer).SendEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// EventStreamer_ServiceDesc is the grpc.ServiceDesc for EventStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sensor.EventStreamer",
	HandlerType: (*EventStreamerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _EventStreamer_SendEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sensor.proto",
}
