// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sensor.proto

package sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED   EventType = 0
	EventType_EVENT_TYPE_INFORMATIONAL EventType = 1
	EventType_EVENT_TYPE_GRANTED       EventType = 2
	EventType_EVENT_TYPE_DENIED        EventType = 3
	EventType_EVENT_TYPE_ERROR         EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_INFORMATIONAL",
		2: "EVENT_TYPE_GRANTED",
		3: "EVENT_TYPE_DENIED",
		4: "EVENT_TYPE_ERROR",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":   0,
		"EVENT_TYPE_INFORMATIONAL": 1,
		"EVENT_TYPE_GRANTED":       2,
		"EVENT_TYPE_DENIED":        3,
		"EVENT_TYPE_ERROR":         4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_sensor_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_sensor_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_sensor_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Host            string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type            EventType              `protobuf:"varint,3,opt,name=type,proto3,enum=sync.EventType" json:"type,omitempty"`
	Address         []byte                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	HardwareAddress []byte                 `protobuf:"bytes,5,opt,name=hardware_address,json=hardwareAddress,proto3" json:"hardware_address,omitempty"`
	User            string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Service         string                 `protobuf:"bytes,7,opt,name=service,proto3" json:"service,omitempty"`
	Sensor          string                 `protobuf:"bytes,8,opt,name=sensor,proto3" json:"sensor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Event) GetHardwareAddress() []byte {
	if x != nil {
		return x.HardwareAddress
	}
	return nil
}

func (x *Event) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Event) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Event) GetSensor() string {
	if x != nil {
		return x.Sensor
	}
	return ""
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_sensor_proto_rawDescGZIP(), []int{1}
}

var File_sensor_proto protoreflect.FileDescriptor

const file_sensor_proto_rawDesc = "" +
	"\n" +
	"\fsensor.proto\x12\x04sync\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\x05Event\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0f.sync.EventTypeR\x04type\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\fR\aaddress\x12)\n" +
	"\x10hardware_address\x18\x05 \x01(\fR\x0fhardwareAddress\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12\x18\n" +
	"\aservice\x18\a \x01(\tR\aservice\x12\x16\n" +
	"\x06sensor\x18\b \x01(\tR\x06sensor\"\x0f\n" +
	"\rEmptyResponse*\x8a\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EVENT_TYPE_INFORMATIONAL\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_GRANTED\x10\x02\x12\x15\n" +
	"\x11EVENT_TYPE_DENIED\x10\x03\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\x042>\n" +
	"\rEventStreamer\x12-\n" +
	"\tSendEvent\x12\v.sync.Event\x1a\x13.sync.EmptyResponseB\bZ\x06./syncb\x06proto3"

var (
	file_sensor_proto_rawDescOnce sync.Once
	file_sensor_proto_rawDescData []byte
)

func file_sensor_proto_rawDescGZIP() []byte {
	file_sensor_proto_rawDescOnce.Do(func() {
		file_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensor_proto_rawDesc), len(file_sensor_proto_rawDesc)))
	})
	return file_sensor_proto_rawDescData
}

var file_sensor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sensor_proto_goTypes = []any{
	(EventType)(0),                // 0: sync.EventType
	(*Event)(nil),                 // 1: sync.Event
	(*EmptyResponse)(nil),         // 2: sync.EmptyResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_sensor_proto_depIdxs = []int32{
	3, // 0: sync.Event.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: sync.Event.type:type_name -> sync.EventType
	1, // 2: sync.EventStreamer.SendEvent:input_type -> sync.Event
	2, // 3: sync.EventStreamer.SendEvent:output_type -> sync.EmptyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sensor_proto_init() }
func file_sensor_proto_init() {
	if File_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensor_proto_rawDesc), len(file_sensor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensor_proto_goTypes,
		DependencyIndexes: file_sensor_proto_depIdxs,
		EnumInfos:         file_sensor_proto_enumTypes,
		MessageInfos:      file_sensor_proto_msgTypes,
	}.Build()
	File_sensor_proto = out.File
	file_sensor_proto_goTypes = nil
	file_sensor_proto_depIdxs = nil
}
